[package]
name = "oracle"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
soroban-sdk = { version = "21.7.7", features = ["alloc"] }

[dev-dependencies]
soroban-sdk = { version = "21.7.7", features = ["alloc", "testutils"] }
ed25519-dalek = { version = "3.0.0", features = ["rand_core"] }
