#!/usr/bin/env bash
# =============================================================================
# snapshot-contract-state.sh
#
# Captures a point-in-time snapshot of a contract's storage keys and struct
# field signatures. Run this BEFORE an upgrade to create the reference files
# that upgrade-safety-check.sh diffs against.
#
# Usage:
#   ./scripts/snapshot-contract-state.sh <contract>
#
# Outputs (to docs/operations/):
#   storage-keys-<contract>.txt   — all DataKey variant names, one per line
#   struct-snapshot-<contract>.txt — public fields for key persistent structs
# =============================================================================

set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; NC='\033[0m'
pass() { echo -e "${GREEN}[OK]${NC}  $*"; }
fail() { echo -e "${RED}[FAIL]${NC}  $*"; exit 1; }

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <contract>"
  exit 2
fi

CONTRACT="$1"
SRC="contracts/${CONTRACT}/src/lib.rs"
OUT_DIR="docs/operations"

if [[ ! -f "$SRC" ]]; then
  fail "Contract source not found: $SRC"
fi

mkdir -p "$OUT_DIR"

# ---------------------------------------------------------------------------
# 1. Storage key snapshot
# ---------------------------------------------------------------------------
KEYS_FILE="$OUT_DIR/storage-keys-${CONTRACT}.txt"

grep -oP '(?<=DataKey::)\w+' "$SRC" | sort -u > "$KEYS_FILE"
COUNT=$(wc -l < "$KEYS_FILE")
pass "Storage key snapshot: $KEYS_FILE ($COUNT variants)"

# ---------------------------------------------------------------------------
# 2. Struct field snapshot
# ---------------------------------------------------------------------------
STRUCT_FILE="$OUT_DIR/struct-snapshot-${CONTRACT}.txt"
KEY_STRUCTS="ProvenanceCert VerificationRequest ProviderSLA CostEstimate ProviderInfo ProviderReputation TeeHashRecord"

{
  echo "# Struct snapshot for $CONTRACT — $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "# Generated by scripts/snapshot-contract-state.sh"
  echo ""
  for STRUCT in $KEY_STRUCTS; do
    FIELDS=$(awk "/pub struct $STRUCT[[:space:]]*\{/,/^}/" "$SRC" 2>/dev/null | grep 'pub ' || true)
    if [[ -n "$FIELDS" ]]; then
      echo "# $STRUCT"
      echo "$FIELDS"
      echo ""
    fi
  done
} > "$STRUCT_FILE"

pass "Struct snapshot: $STRUCT_FILE"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "Snapshots written. Commit these files before upgrading:"
echo "  git add $KEYS_FILE $STRUCT_FILE"
echo "  git commit -m 'chore: pre-upgrade storage snapshot for $CONTRACT'"
echo ""
echo "After deploying the upgrade, run:"
echo "  ./scripts/snapshot-contract-state.sh $CONTRACT"
echo "to update the snapshots to the new version."
